import type { Employee } from '@/types/employee';
import type { Department } from '@/types/department';
import type { DashboardStats, StatCardData, ChartDataPoint } from '@/types/dashboard';
import type { AttendanceRecord, AttendanceSummary } from '@/types/attendance';
import type { LeaveRequest, LeaveBalance } from '@/types/leave';

// ---------------------------------------------------------------------------
// Departments
// ---------------------------------------------------------------------------

export const mockDepartments: Department[] = [
  {
    id: 'dept-1',
    name: 'Engineering',
    description: 'Software development and technical infrastructure',
    headOfDepartment: 'Alice Johnson',
    headOfDepartmentId: 'emp-1',
    employeeCount: 8,
    status: 'active',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2024-11-20T14:30:00Z',
  },
  {
    id: 'dept-2',
    name: 'Design',
    description: 'Product design, UX research, and brand identity',
    headOfDepartment: 'Marcus Lee',
    headOfDepartmentId: 'emp-5',
    employeeCount: 4,
    status: 'active',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2024-10-05T11:15:00Z',
  },
  {
    id: 'dept-3',
    name: 'Marketing',
    description: 'Digital marketing, content strategy, and growth',
    headOfDepartment: 'Sarah Chen',
    headOfDepartmentId: 'emp-9',
    employeeCount: 3,
    status: 'active',
    createdAt: '2023-02-01T09:00:00Z',
    updatedAt: '2024-09-18T16:45:00Z',
  },
  {
    id: 'dept-4',
    name: 'Sales',
    description: 'Business development, account management, and revenue',
    headOfDepartment: 'James Wilson',
    headOfDepartmentId: 'emp-12',
    employeeCount: 2,
    status: 'active',
    createdAt: '2023-02-01T09:00:00Z',
    updatedAt: '2024-08-22T10:00:00Z',
  },
  {
    id: 'dept-5',
    name: 'Human Resources',
    description: 'Talent acquisition, employee relations, and compliance',
    headOfDepartment: 'Priya Patel',
    headOfDepartmentId: 'emp-14',
    employeeCount: 2,
    status: 'active',
    createdAt: '2023-01-15T09:00:00Z',
    updatedAt: '2024-12-01T09:30:00Z',
  },
  {
    id: 'dept-6',
    name: 'Finance',
    description: 'Accounting, budgeting, financial planning and analysis',
    headOfDepartment: 'Robert Kim',
    headOfDepartmentId: 'emp-16',
    employeeCount: 1,
    status: 'inactive',
    createdAt: '2023-03-10T09:00:00Z',
    updatedAt: '2024-07-15T13:20:00Z',
  },
];

// ---------------------------------------------------------------------------
// Employees
// ---------------------------------------------------------------------------

export const mockEmployees: Employee[] = [
  {
    id: 'emp-1',
    employeeId: 'EMP-001',
    firstName: 'Alice',
    lastName: 'Johnson',
    email: 'alice.johnson@company.com',
    phone: '+1 (555) 101-2001',
    avatar: `${import.meta.env.BASE_URL}avatars/alice.jpg`,
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'VP of Engineering',
    status: 'active',
    joiningDate: '2021-03-15',
    salary: 185000,
    address: {
      street: '742 Evergreen Terrace',
      city: 'San Francisco',
      state: 'California',
      zipCode: '94102',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Tom Johnson',
      relationship: 'Spouse',
      phone: '+1 (555) 101-3001',
    },
    createdAt: '2021-03-15T09:00:00Z',
    updatedAt: '2024-11-10T14:30:00Z',
  },
  {
    id: 'emp-2',
    employeeId: 'EMP-002',
    firstName: 'Brian',
    lastName: 'Martinez',
    email: 'brian.martinez@company.com',
    phone: '+1 (555) 102-2002',
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'Senior Software Engineer',
    status: 'active',
    joiningDate: '2021-06-01',
    salary: 155000,
    address: {
      street: '1234 Oak Avenue',
      city: 'San Jose',
      state: 'California',
      zipCode: '95131',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Maria Martinez',
      relationship: 'Mother',
      phone: '+1 (555) 102-3002',
    },
    createdAt: '2021-06-01T09:00:00Z',
    updatedAt: '2024-10-15T11:20:00Z',
  },
  {
    id: 'emp-3',
    employeeId: 'EMP-003',
    firstName: 'Catherine',
    lastName: 'Nguyen',
    email: 'catherine.nguyen@company.com',
    phone: '+1 (555) 103-2003',
    avatar: `${import.meta.env.BASE_URL}avatars/catherine.jpg`,
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'Software Engineer',
    status: 'active',
    joiningDate: '2022-01-10',
    salary: 125000,
    address: {
      street: '567 Pine Street',
      city: 'Oakland',
      state: 'California',
      zipCode: '94612',
      country: 'United States',
    },
    emergencyContact: {
      name: 'David Nguyen',
      relationship: 'Brother',
      phone: '+1 (555) 103-3003',
    },
    createdAt: '2022-01-10T09:00:00Z',
    updatedAt: '2024-09-20T16:45:00Z',
  },
  {
    id: 'emp-4',
    employeeId: 'EMP-004',
    firstName: 'Daniel',
    lastName: "O'Brien",
    email: 'daniel.obrien@company.com',
    phone: '+1 (555) 104-2004',
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'DevOps Engineer',
    status: 'on-leave',
    joiningDate: '2022-04-18',
    salary: 140000,
    address: {
      street: '890 Maple Drive',
      city: 'Berkeley',
      state: 'California',
      zipCode: '94704',
      country: 'United States',
    },
    emergencyContact: {
      name: "Linda O'Brien",
      relationship: 'Wife',
      phone: '+1 (555) 104-3004',
    },
    createdAt: '2022-04-18T09:00:00Z',
    updatedAt: '2024-12-01T08:00:00Z',
  },
  {
    id: 'emp-5',
    employeeId: 'EMP-005',
    firstName: 'Marcus',
    lastName: 'Lee',
    email: 'marcus.lee@company.com',
    phone: '+1 (555) 105-2005',
    avatar: `${import.meta.env.BASE_URL}avatars/marcus.jpg`,
    department: 'Design',
    departmentId: 'dept-2',
    designation: 'Head of Design',
    status: 'active',
    joiningDate: '2021-05-20',
    salary: 160000,
    address: {
      street: '321 Cedar Lane',
      city: 'Palo Alto',
      state: 'California',
      zipCode: '94301',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Jenny Lee',
      relationship: 'Sister',
      phone: '+1 (555) 105-3005',
    },
    createdAt: '2021-05-20T09:00:00Z',
    updatedAt: '2024-11-25T10:00:00Z',
  },
  {
    id: 'emp-6',
    employeeId: 'EMP-006',
    firstName: 'Emma',
    lastName: 'Davis',
    email: 'emma.davis@company.com',
    phone: '+1 (555) 106-2006',
    department: 'Design',
    departmentId: 'dept-2',
    designation: 'Senior UX Designer',
    status: 'active',
    joiningDate: '2022-02-14',
    salary: 130000,
    address: {
      street: '456 Birch Road',
      city: 'Mountain View',
      state: 'California',
      zipCode: '94041',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Michael Davis',
      relationship: 'Father',
      phone: '+1 (555) 106-3006',
    },
    createdAt: '2022-02-14T09:00:00Z',
    updatedAt: '2024-10-30T15:10:00Z',
  },
  {
    id: 'emp-7',
    employeeId: 'EMP-007',
    firstName: 'Fatima',
    lastName: 'Al-Hassan',
    email: 'fatima.alhassan@company.com',
    phone: '+1 (555) 107-2007',
    avatar: `${import.meta.env.BASE_URL}avatars/fatima.jpg`,
    department: 'Design',
    departmentId: 'dept-2',
    designation: 'UI Designer',
    status: 'active',
    joiningDate: '2023-03-01',
    salary: 105000,
    address: {
      street: '789 Willow Way',
      city: 'Sunnyvale',
      state: 'California',
      zipCode: '94086',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Ahmed Al-Hassan',
      relationship: 'Husband',
      phone: '+1 (555) 107-3007',
    },
    createdAt: '2023-03-01T09:00:00Z',
    updatedAt: '2024-11-05T12:30:00Z',
  },
  {
    id: 'emp-8',
    employeeId: 'EMP-008',
    firstName: 'George',
    lastName: 'Thompson',
    email: 'george.thompson@company.com',
    phone: '+1 (555) 108-2008',
    department: 'Design',
    departmentId: 'dept-2',
    designation: 'UX Researcher',
    status: 'inactive',
    joiningDate: '2022-08-15',
    salary: 110000,
    address: {
      street: '234 Elm Court',
      city: 'Redwood City',
      state: 'California',
      zipCode: '94063',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Susan Thompson',
      relationship: 'Wife',
      phone: '+1 (555) 108-3008',
    },
    createdAt: '2022-08-15T09:00:00Z',
    updatedAt: '2024-06-30T09:00:00Z',
  },
  {
    id: 'emp-9',
    employeeId: 'EMP-009',
    firstName: 'Sarah',
    lastName: 'Chen',
    email: 'sarah.chen@company.com',
    phone: '+1 (555) 109-2009',
    avatar: `${import.meta.env.BASE_URL}avatars/sarah.jpg`,
    department: 'Marketing',
    departmentId: 'dept-3',
    designation: 'Marketing Director',
    status: 'active',
    joiningDate: '2021-09-01',
    salary: 150000,
    address: {
      street: '678 Spruce Boulevard',
      city: 'San Mateo',
      state: 'California',
      zipCode: '94401',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Wei Chen',
      relationship: 'Mother',
      phone: '+1 (555) 109-3009',
    },
    createdAt: '2021-09-01T09:00:00Z',
    updatedAt: '2024-12-05T14:00:00Z',
  },
  {
    id: 'emp-10',
    employeeId: 'EMP-010',
    firstName: 'Kevin',
    lastName: 'Wright',
    email: 'kevin.wright@company.com',
    phone: '+1 (555) 110-2010',
    department: 'Marketing',
    departmentId: 'dept-3',
    designation: 'Content Strategist',
    status: 'active',
    joiningDate: '2023-01-23',
    salary: 95000,
    address: {
      street: '901 Ash Street',
      city: 'Fremont',
      state: 'California',
      zipCode: '94536',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Laura Wright',
      relationship: 'Wife',
      phone: '+1 (555) 110-3010',
    },
    createdAt: '2023-01-23T09:00:00Z',
    updatedAt: '2024-11-18T09:45:00Z',
  },
  {
    id: 'emp-11',
    employeeId: 'EMP-011',
    firstName: 'Olivia',
    lastName: 'Hernandez',
    email: 'olivia.hernandez@company.com',
    phone: '+1 (555) 111-2011',
    department: 'Marketing',
    departmentId: 'dept-3',
    designation: 'Growth Marketing Manager',
    status: 'active',
    joiningDate: '2023-06-12',
    salary: 115000,
    address: {
      street: '345 Poplar Avenue',
      city: 'Santa Clara',
      state: 'California',
      zipCode: '95050',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Carlos Hernandez',
      relationship: 'Brother',
      phone: '+1 (555) 111-3011',
    },
    createdAt: '2023-06-12T09:00:00Z',
    updatedAt: '2024-10-22T11:30:00Z',
  },
  {
    id: 'emp-12',
    employeeId: 'EMP-012',
    firstName: 'James',
    lastName: 'Wilson',
    email: 'james.wilson@company.com',
    phone: '+1 (555) 112-2012',
    avatar: `${import.meta.env.BASE_URL}avatars/james.jpg`,
    department: 'Sales',
    departmentId: 'dept-4',
    designation: 'Sales Director',
    status: 'active',
    joiningDate: '2021-07-05',
    salary: 145000,
    address: {
      street: '567 Magnolia Drive',
      city: 'Cupertino',
      state: 'California',
      zipCode: '95014',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Rachel Wilson',
      relationship: 'Wife',
      phone: '+1 (555) 112-3012',
    },
    createdAt: '2021-07-05T09:00:00Z',
    updatedAt: '2024-11-28T16:00:00Z',
  },
  {
    id: 'emp-13',
    employeeId: 'EMP-013',
    firstName: 'Nathan',
    lastName: 'Brooks',
    email: 'nathan.brooks@company.com',
    phone: '+1 (555) 113-2013',
    department: 'Sales',
    departmentId: 'dept-4',
    designation: 'Account Executive',
    status: 'active',
    joiningDate: '2023-09-04',
    salary: 90000,
    address: {
      street: '123 Dogwood Lane',
      city: 'Campbell',
      state: 'California',
      zipCode: '95008',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Diane Brooks',
      relationship: 'Mother',
      phone: '+1 (555) 113-3013',
    },
    createdAt: '2023-09-04T09:00:00Z',
    updatedAt: '2024-12-02T10:15:00Z',
  },
  {
    id: 'emp-14',
    employeeId: 'EMP-014',
    firstName: 'Priya',
    lastName: 'Patel',
    email: 'priya.patel@company.com',
    phone: '+1 (555) 114-2014',
    avatar: `${import.meta.env.BASE_URL}avatars/priya.jpg`,
    department: 'Human Resources',
    departmentId: 'dept-5',
    designation: 'HR Director',
    status: 'active',
    joiningDate: '2021-02-01',
    salary: 140000,
    address: {
      street: '890 Laurel Street',
      city: 'Los Gatos',
      state: 'California',
      zipCode: '95032',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Raj Patel',
      relationship: 'Husband',
      phone: '+1 (555) 114-3014',
    },
    createdAt: '2021-02-01T09:00:00Z',
    updatedAt: '2024-12-10T09:00:00Z',
  },
  {
    id: 'emp-15',
    employeeId: 'EMP-015',
    firstName: 'Sophia',
    lastName: 'Rivera',
    email: 'sophia.rivera@company.com',
    phone: '+1 (555) 115-2015',
    department: 'Human Resources',
    departmentId: 'dept-5',
    designation: 'HR Specialist',
    status: 'active',
    joiningDate: '2023-04-17',
    salary: 85000,
    address: {
      street: '456 Hawthorn Place',
      city: 'Milpitas',
      state: 'California',
      zipCode: '95035',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Elena Rivera',
      relationship: 'Sister',
      phone: '+1 (555) 115-3015',
    },
    createdAt: '2023-04-17T09:00:00Z',
    updatedAt: '2024-11-12T13:45:00Z',
  },
  {
    id: 'emp-16',
    employeeId: 'EMP-016',
    firstName: 'Robert',
    lastName: 'Kim',
    email: 'robert.kim@company.com',
    phone: '+1 (555) 116-2016',
    department: 'Finance',
    departmentId: 'dept-6',
    designation: 'Finance Manager',
    status: 'active',
    joiningDate: '2022-05-09',
    salary: 135000,
    address: {
      street: '234 Sequoia Court',
      city: 'Saratoga',
      state: 'California',
      zipCode: '95070',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Grace Kim',
      relationship: 'Wife',
      phone: '+1 (555) 116-3016',
    },
    createdAt: '2022-05-09T09:00:00Z',
    updatedAt: '2024-10-28T15:30:00Z',
  },
  {
    id: 'emp-17',
    employeeId: 'EMP-017',
    firstName: 'Tyler',
    lastName: 'Adams',
    email: 'tyler.adams@company.com',
    phone: '+1 (555) 117-2017',
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'Frontend Engineer',
    status: 'active',
    joiningDate: '2023-07-24',
    salary: 120000,
    address: {
      street: '678 Redwood Avenue',
      city: 'Menlo Park',
      state: 'California',
      zipCode: '94025',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Karen Adams',
      relationship: 'Mother',
      phone: '+1 (555) 117-3017',
    },
    createdAt: '2023-07-24T09:00:00Z',
    updatedAt: '2024-11-30T11:00:00Z',
  },
  {
    id: 'emp-18',
    employeeId: 'EMP-018',
    firstName: 'Hannah',
    lastName: 'Garcia',
    email: 'hannah.garcia@company.com',
    phone: '+1 (555) 118-2018',
    avatar: `${import.meta.env.BASE_URL}avatars/hannah.jpg`,
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'Backend Engineer',
    status: 'active',
    joiningDate: '2023-10-02',
    salary: 125000,
    address: {
      street: '901 Cypress Way',
      city: 'Daly City',
      state: 'California',
      zipCode: '94014',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Luis Garcia',
      relationship: 'Father',
      phone: '+1 (555) 118-3018',
    },
    createdAt: '2023-10-02T09:00:00Z',
    updatedAt: '2024-12-08T14:20:00Z',
  },
  {
    id: 'emp-19',
    employeeId: 'EMP-019',
    firstName: 'Isaac',
    lastName: 'Taylor',
    email: 'isaac.taylor@company.com',
    phone: '+1 (555) 119-2019',
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'QA Engineer',
    status: 'terminated',
    joiningDate: '2022-11-14',
    salary: 100000,
    address: {
      street: '345 Juniper Circle',
      city: 'South San Francisco',
      state: 'California',
      zipCode: '94080',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Vanessa Taylor',
      relationship: 'Sister',
      phone: '+1 (555) 119-3019',
    },
    createdAt: '2022-11-14T09:00:00Z',
    updatedAt: '2024-05-15T09:00:00Z',
  },
  {
    id: 'emp-20',
    employeeId: 'EMP-020',
    firstName: 'Liam',
    lastName: 'Scott',
    email: 'liam.scott@company.com',
    phone: '+1 (555) 120-2020',
    department: 'Engineering',
    departmentId: 'dept-1',
    designation: 'Full Stack Engineer',
    status: 'active',
    joiningDate: '2024-01-08',
    salary: 130000,
    address: {
      street: '567 Sycamore Drive',
      city: 'Foster City',
      state: 'California',
      zipCode: '94404',
      country: 'United States',
    },
    emergencyContact: {
      name: 'Patricia Scott',
      relationship: 'Mother',
      phone: '+1 (555) 120-3020',
    },
    createdAt: '2024-01-08T09:00:00Z',
    updatedAt: '2024-12-12T10:45:00Z',
  },
];

// ---------------------------------------------------------------------------
// Dashboard Stats
// ---------------------------------------------------------------------------

export const mockDashboardStats: DashboardStats = {
  totalEmployees: 20,
  activeEmployees: 16,
  departments: 6,
  newHires: 3,
  attendanceRate: 92.5,
  payrollStatus: 'Processed',
};

export const mockStatCards: StatCardData[] = [
  {
    title: 'Total Employees',
    value: 20,
    change: 8.2,
    changeLabel: 'from last month',
    icon: 'Users',
    trend: 'up',
  },
  {
    title: 'Active Employees',
    value: 16,
    change: 4.1,
    changeLabel: 'from last month',
    icon: 'UserCheck',
    trend: 'up',
  },
  {
    title: 'Departments',
    value: 6,
    change: 0,
    changeLabel: 'no change',
    icon: 'Building2',
    trend: 'neutral',
  },
  {
    title: 'Attendance Rate',
    value: '92.5%',
    change: -1.3,
    changeLabel: 'from last month',
    icon: 'CalendarCheck',
    trend: 'down',
  },
];

// ---------------------------------------------------------------------------
// Chart Data
// ---------------------------------------------------------------------------

export const employeeGrowthData: ChartDataPoint[] = [
  { name: 'Jan', value: 12, hires: 2, departures: 0 },
  { name: 'Feb', value: 13, hires: 1, departures: 0 },
  { name: 'Mar', value: 14, hires: 2, departures: 1 },
  { name: 'Apr', value: 15, hires: 1, departures: 0 },
  { name: 'May', value: 15, hires: 1, departures: 1 },
  { name: 'Jun', value: 16, hires: 2, departures: 1 },
  { name: 'Jul', value: 17, hires: 1, departures: 0 },
  { name: 'Aug', value: 17, hires: 1, departures: 1 },
  { name: 'Sep', value: 18, hires: 2, departures: 1 },
  { name: 'Oct', value: 19, hires: 1, departures: 0 },
  { name: 'Nov', value: 19, hires: 1, departures: 1 },
  { name: 'Dec', value: 20, hires: 2, departures: 1 },
];

export const departmentDistributionData: ChartDataPoint[] = [
  { name: 'Engineering', value: 8 },
  { name: 'Design', value: 4 },
  { name: 'Marketing', value: 3 },
  { name: 'Sales', value: 2 },
  { name: 'HR', value: 2 },
  { name: 'Finance', value: 1 },
];

export const attendanceChartData: ChartDataPoint[] = [
  { name: 'Mon', value: 18, present: 16, absent: 1, late: 1 },
  { name: 'Tue', value: 18, present: 17, absent: 0, late: 1 },
  { name: 'Wed', value: 18, present: 15, absent: 2, late: 1 },
  { name: 'Thu', value: 18, present: 16, absent: 1, late: 1 },
  { name: 'Fri', value: 18, present: 14, absent: 2, late: 2 },
  { name: 'Sat', value: 5, present: 5, absent: 0, late: 0 },
  { name: 'Sun', value: 0, present: 0, absent: 0, late: 0 },
];

export const hiringTrendData: ChartDataPoint[] = [
  { name: 'Jan', value: 2, applications: 45, interviews: 12 },
  { name: 'Feb', value: 1, applications: 38, interviews: 8 },
  { name: 'Mar', value: 2, applications: 52, interviews: 15 },
  { name: 'Apr', value: 1, applications: 41, interviews: 10 },
  { name: 'May', value: 1, applications: 36, interviews: 9 },
  { name: 'Jun', value: 2, applications: 48, interviews: 14 },
  { name: 'Jul', value: 1, applications: 33, interviews: 7 },
  { name: 'Aug', value: 1, applications: 29, interviews: 6 },
  { name: 'Sep', value: 2, applications: 55, interviews: 16 },
  { name: 'Oct', value: 1, applications: 42, interviews: 11 },
  { name: 'Nov', value: 1, applications: 37, interviews: 9 },
  { name: 'Dec', value: 2, applications: 50, interviews: 13 },
];

// ---------------------------------------------------------------------------
// Attendance Records
// ---------------------------------------------------------------------------

export const mockAttendanceRecords: AttendanceRecord[] = [
  {
    id: 'att-1',
    employeeId: 'emp-1',
    employeeName: 'Alice Johnson',
    date: '2024-12-16',
    checkIn: '08:55',
    checkOut: '17:30',
    status: 'present',
    workHours: 8.58,
  },
  {
    id: 'att-2',
    employeeId: 'emp-2',
    employeeName: 'Brian Martinez',
    date: '2024-12-16',
    checkIn: '09:15',
    checkOut: '18:00',
    status: 'late',
    workHours: 8.75,
    notes: 'Traffic delay on I-280',
  },
  {
    id: 'att-3',
    employeeId: 'emp-3',
    employeeName: 'Catherine Nguyen',
    date: '2024-12-16',
    checkIn: '08:45',
    checkOut: '17:15',
    status: 'present',
    workHours: 8.5,
  },
  {
    id: 'att-4',
    employeeId: 'emp-4',
    employeeName: "Daniel O'Brien",
    date: '2024-12-16',
    checkIn: null,
    checkOut: null,
    status: 'on-leave',
    workHours: null,
    notes: 'Paternity leave',
  },
  {
    id: 'att-5',
    employeeId: 'emp-5',
    employeeName: 'Marcus Lee',
    date: '2024-12-16',
    checkIn: '08:30',
    checkOut: '17:45',
    status: 'present',
    workHours: 9.25,
  },
  {
    id: 'att-6',
    employeeId: 'emp-6',
    employeeName: 'Emma Davis',
    date: '2024-12-16',
    checkIn: '09:00',
    checkOut: '13:00',
    status: 'half-day',
    workHours: 4.0,
    notes: 'Doctor appointment in afternoon',
  },
  {
    id: 'att-7',
    employeeId: 'emp-7',
    employeeName: 'Fatima Al-Hassan',
    date: '2024-12-16',
    checkIn: '08:50',
    checkOut: '17:20',
    status: 'present',
    workHours: 8.5,
  },
  {
    id: 'att-8',
    employeeId: 'emp-9',
    employeeName: 'Sarah Chen',
    date: '2024-12-16',
    checkIn: null,
    checkOut: null,
    status: 'absent',
    workHours: null,
    notes: 'Called in sick',
  },
  {
    id: 'att-9',
    employeeId: 'emp-10',
    employeeName: 'Kevin Wright',
    date: '2024-12-16',
    checkIn: '08:40',
    checkOut: '17:10',
    status: 'present',
    workHours: 8.5,
  },
  {
    id: 'att-10',
    employeeId: 'emp-11',
    employeeName: 'Olivia Hernandez',
    date: '2024-12-16',
    checkIn: '09:05',
    checkOut: '17:35',
    status: 'late',
    workHours: 8.5,
  },
  {
    id: 'att-11',
    employeeId: 'emp-12',
    employeeName: 'James Wilson',
    date: '2024-12-16',
    checkIn: '08:25',
    checkOut: '18:15',
    status: 'present',
    workHours: 9.83,
  },
  {
    id: 'att-12',
    employeeId: 'emp-13',
    employeeName: 'Nathan Brooks',
    date: '2024-12-16',
    checkIn: '08:58',
    checkOut: '17:28',
    status: 'present',
    workHours: 8.5,
  },
  {
    id: 'att-13',
    employeeId: 'emp-14',
    employeeName: 'Priya Patel',
    date: '2024-12-16',
    checkIn: '08:35',
    checkOut: '17:05',
    status: 'present',
    workHours: 8.5,
  },
  {
    id: 'att-14',
    employeeId: 'emp-15',
    employeeName: 'Sophia Rivera',
    date: '2024-12-16',
    checkIn: '08:48',
    checkOut: '17:18',
    status: 'present',
    workHours: 8.5,
  },
  {
    id: 'att-15',
    employeeId: 'emp-17',
    employeeName: 'Tyler Adams',
    date: '2024-12-16',
    checkIn: '09:20',
    checkOut: '18:20',
    status: 'late',
    workHours: 9.0,
    notes: 'Standup at home first',
  },
];

// ---------------------------------------------------------------------------
// Attendance Summary (for individual employee view)
// ---------------------------------------------------------------------------

export const mockAttendanceSummary: AttendanceSummary = {
  totalDays: 22,
  presentDays: 18,
  absentDays: 1,
  lateDays: 1,
  halfDays: 1,
  leaveDays: 1,
  attendanceRate: 90.9,
};

// ---------------------------------------------------------------------------
// Leave Requests
// ---------------------------------------------------------------------------

export const mockLeaveRequests: LeaveRequest[] = [
  {
    id: 'lv-1',
    employeeId: 'emp-4',
    employeeName: "Daniel O'Brien",
    type: 'paternity',
    startDate: '2024-12-01',
    endDate: '2024-12-31',
    days: 22,
    reason: 'Paternity leave for the birth of my second child.',
    status: 'approved',
    approvedBy: 'Priya Patel',
    createdAt: '2024-11-15T09:00:00Z',
    updatedAt: '2024-11-16T11:00:00Z',
  },
  {
    id: 'lv-2',
    employeeId: 'emp-9',
    employeeName: 'Sarah Chen',
    employeeAvatar: `${import.meta.env.BASE_URL}avatars/sarah.jpg`,
    type: 'sick',
    startDate: '2024-12-16',
    endDate: '2024-12-17',
    days: 2,
    reason: 'Flu symptoms, need rest and recovery.',
    status: 'approved',
    approvedBy: 'Priya Patel',
    createdAt: '2024-12-15T20:00:00Z',
    updatedAt: '2024-12-16T07:30:00Z',
  },
  {
    id: 'lv-3',
    employeeId: 'emp-3',
    employeeName: 'Catherine Nguyen',
    employeeAvatar: `${import.meta.env.BASE_URL}avatars/catherine.jpg`,
    type: 'annual',
    startDate: '2024-12-23',
    endDate: '2024-12-27',
    days: 5,
    reason: 'Holiday vacation with family traveling to Vietnam.',
    status: 'pending',
    createdAt: '2024-12-10T14:00:00Z',
    updatedAt: '2024-12-10T14:00:00Z',
  },
  {
    id: 'lv-4',
    employeeId: 'emp-6',
    employeeName: 'Emma Davis',
    type: 'personal',
    startDate: '2024-12-20',
    endDate: '2024-12-20',
    days: 1,
    reason: 'Moving to a new apartment, need the day off for logistics.',
    status: 'approved',
    approvedBy: 'Marcus Lee',
    createdAt: '2024-12-08T10:00:00Z',
    updatedAt: '2024-12-09T09:15:00Z',
  },
  {
    id: 'lv-5',
    employeeId: 'emp-10',
    employeeName: 'Kevin Wright',
    type: 'annual',
    startDate: '2025-01-02',
    endDate: '2025-01-10',
    days: 7,
    reason: 'Extended New Year vacation planned months ago.',
    status: 'pending',
    createdAt: '2024-12-01T16:00:00Z',
    updatedAt: '2024-12-01T16:00:00Z',
  },
  {
    id: 'lv-6',
    employeeId: 'emp-13',
    employeeName: 'Nathan Brooks',
    type: 'sick',
    startDate: '2024-12-12',
    endDate: '2024-12-13',
    days: 2,
    reason: 'Dental surgery and recovery period.',
    status: 'approved',
    approvedBy: 'James Wilson',
    createdAt: '2024-12-10T08:30:00Z',
    updatedAt: '2024-12-10T09:00:00Z',
  },
  {
    id: 'lv-7',
    employeeId: 'emp-17',
    employeeName: 'Tyler Adams',
    type: 'annual',
    startDate: '2025-01-15',
    endDate: '2025-01-17',
    days: 3,
    reason: "Attending a friend's wedding out of state.",
    status: 'pending',
    createdAt: '2024-12-14T12:00:00Z',
    updatedAt: '2024-12-14T12:00:00Z',
  },
  {
    id: 'lv-8',
    employeeId: 'emp-2',
    employeeName: 'Brian Martinez',
    type: 'unpaid',
    startDate: '2024-11-25',
    endDate: '2024-11-29',
    days: 5,
    reason: 'Extended personal travel after exhausting PTO balance.',
    status: 'rejected',
    approvedBy: 'Alice Johnson',
    createdAt: '2024-11-10T15:00:00Z',
    updatedAt: '2024-11-12T10:00:00Z',
  },
  {
    id: 'lv-9',
    employeeId: 'emp-15',
    employeeName: 'Sophia Rivera',
    type: 'personal',
    startDate: '2024-12-18',
    endDate: '2024-12-19',
    days: 2,
    reason: 'Attending a family event that requires travel.',
    status: 'cancelled',
    createdAt: '2024-12-05T09:00:00Z',
    updatedAt: '2024-12-12T14:00:00Z',
  },
  {
    id: 'lv-10',
    employeeId: 'emp-18',
    employeeName: 'Hannah Garcia',
    employeeAvatar: `${import.meta.env.BASE_URL}avatars/hannah.jpg`,
    type: 'maternity',
    startDate: '2025-02-01',
    endDate: '2025-04-30',
    days: 63,
    reason: 'Maternity leave for expected delivery in early February.',
    status: 'approved',
    approvedBy: 'Alice Johnson',
    createdAt: '2024-11-20T11:00:00Z',
    updatedAt: '2024-11-22T09:30:00Z',
  },
];

// ---------------------------------------------------------------------------
// Leave Balances (for current logged-in user mock)
// ---------------------------------------------------------------------------

export const mockLeaveBalances: LeaveBalance[] = [
  { type: 'annual', total: 20, used: 12, remaining: 8 },
  { type: 'sick', total: 10, used: 3, remaining: 7 },
  { type: 'personal', total: 5, used: 2, remaining: 3 },
  { type: 'maternity', total: 90, used: 0, remaining: 90 },
  { type: 'paternity', total: 30, used: 0, remaining: 30 },
  { type: 'unpaid', total: 0, used: 0, remaining: 0 },
];

// ---------------------------------------------------------------------------
// Dashboard Chart Data (named exports matching dashboard component usage)
// ---------------------------------------------------------------------------

export const mockEmployeeGrowthData = [
  { month: 'Apr', employees: 142 },
  { month: 'May', employees: 148 },
  { month: 'Jun', employees: 152 },
  { month: 'Jul', employees: 156 },
  { month: 'Aug', employees: 161 },
  { month: 'Sep', employees: 165 },
  { month: 'Oct', employees: 170 },
  { month: 'Nov', employees: 174 },
  { month: 'Dec', employees: 178 },
  { month: 'Jan', employees: 184 },
  { month: 'Feb', employees: 190 },
  { month: 'Mar', employees: 196 },
];

export const mockDepartmentDistribution = [
  { name: 'Engineering', value: 45, color: '#6366f1' },
  { name: 'Design', value: 18, color: '#8b5cf6' },
  { name: 'Marketing', value: 22, color: '#ec4899' },
  { name: 'Human Resources', value: 12, color: '#f59e0b' },
  { name: 'Finance', value: 15, color: '#10b981' },
];

export const mockAttendanceChartData = [
  { day: 'Mon', present: 156, absent: 8, late: 12 },
  { day: 'Tue', present: 162, absent: 5, late: 9 },
  { day: 'Wed', present: 158, absent: 10, late: 8 },
  { day: 'Thu', present: 160, absent: 6, late: 10 },
  { day: 'Fri', present: 148, absent: 18, late: 10 },
];

export const mockHiringTrendData = [
  { month: 'Apr', hires: 8, departures: 3 },
  { month: 'May', hires: 6, departures: 2 },
  { month: 'Jun', hires: 10, departures: 4 },
  { month: 'Jul', hires: 5, departures: 1 },
  { month: 'Aug', hires: 7, departures: 2 },
  { month: 'Sep', hires: 9, departures: 5 },
  { month: 'Oct', hires: 6, departures: 1 },
  { month: 'Nov', hires: 4, departures: 3 },
  { month: 'Dec', hires: 3, departures: 2 },
  { month: 'Jan', hires: 11, departures: 5 },
  { month: 'Feb', hires: 8, departures: 2 },
  { month: 'Mar', hires: 7, departures: 1 },
];
